# -*- coding: utf-8 -*-
"""ِAi_Sans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hi9ejh1cbHtylLLqPbXYFReRdUZHspT
"""

# ============================================
# HR Chatbot (Employees + Policies via RAG)
# - Hybrid intent (keywords + LLM + WordNet)
# - Employee answers + Policy answers with source
# - Conversation memory + session timeout
# ============================================



import os, re, json, time
import pandas as pd, numpy as np
from dotenv import load_dotenv
from openai import OpenAI
from sentence_transformers import CrossEncoder
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.docstore.document import Document
from rank_bm25 import BM25Okapi

# --- WordNet expansion for English synonyms ---
import nltk
nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)
from nltk.corpus import wordnet as wn


# ==============================
# 0) API key & file paths
# ==============================
load_dotenv() 
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

EMP_PATH    = os.path.join(BASE_DIR, "Fikrah_cleaned.xlsx")
POLICY_PATH = os.path.join(BASE_DIR, "Fikrah P&C policy .xlsx")
FAISS_DIR   = os.path.join(BASE_DIR, "faiss_hr_index")


# Global memory (conversation only – no LAST_EMPLOYEE now)
conversation_history: list[dict] = []   # will be loaded later from JSON

# ==============================
# 1) Load Employees
# ==============================
employees = pd.read_excel(EMP_PATH)
employees.columns = employees.columns.str.strip().str.lower()

# Map common aliases -> unified keys
aliases = {
    "employee_id":   ["employee_number", "emp id", "emp_id"],
    "email":         ["email_address", "email"],
    "name":          ["full_name", "full_name_en", "name"],
    "job_title":     ["job_name", "position_name"],
    "department":    ["dept_name", "organization_name", "section_name"],
    "leave_balance": ["accrual"],
    "location_name": ["location_name"],
    "grade_name":    ["grade_name"],
}
for k, alts in aliases.items():
    for a in alts:
        if a.lower() in employees.columns:
            employees = employees.rename(columns={a.lower(): k})

print("✅ Loaded Employees:", len(employees))

# ==============================
# 2) Load Policies + Build FAISS
# ==============================
df = pd.read_excel(POLICY_PATH)

def best_text(row):
    """Pick the best available text for policy search."""
    t = str(row.get("Exact_Rule_Summary", "") or "").strip()
    if not t:
        t = str(row.get("Evidence/Notes", "") or "").strip()
    if not t:
        t = " - ".join(
            [
                str(row.get("Policy_Chapter", "") or ""),
                str(row.get("Policy_Title", "") or ""),
            ]
        ).strip(" -")
    return t

df["text"] = df.apply(best_text, axis=1)

docs = []
for _, row in df.iterrows():
    txt = str(row["text"])
    if len(txt) <= 10:
        continue

    docs.append(
        Document(
            page_content="passage: " + txt,
            metadata={
                "title":      str(row.get("Policy_Title", "") or ""),
                "policy_no":  str(row.get("Clause_ID", "") or ""),
                "department": str(row.get("Policy_Chapter", "") or ""),
            },
        )
    )

embeddings = HuggingFaceEmbeddings(model_name="intfloat/multilingual-e5-large")
vs = FAISS.from_documents(docs, embeddings)
vs.save_local(FAISS_DIR)
print("✅ Policies indexed:", len(docs))

# Optional keyword retriever (not used below but handy)
TOKENS = [d.page_content.lower().split() for d in docs]
bm25 = BM25Okapi(TOKENS)

# Cross-encoder for light reranking
cross_enc = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

# ==============================
# 3) Common helpers
# ==============================
def detect_lang(text: str) -> str:
    """Return 'ar' if Arabic letters are present else 'en'."""
    return "ar" if re.search(r"[\u0600-\u06FF]", text or "") else "en"

def llm_call(messages, model: str = "gpt-4o-mini", temperature: float = 0.0) -> str:
    """Wrapper for OpenAI chat completions."""
    r = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature,
    )
    return r.choices[0].message.content

def make_json_safe(obj):
    """Convert pandas/numpy/Timestamp values into JSON-safe Python types."""
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if obj is None or (isinstance(obj, float) and np.isnan(obj)):
        return None
    if isinstance(obj, (pd.Timestamp,)):
        return obj.date().isoformat()
    if isinstance(obj, (pd.Series,)):
        return {k: make_json_safe(v) for k, v in obj.to_dict().items()}
    if isinstance(obj, (dict,)):
        return {k: make_json_safe(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [make_json_safe(v) for v in obj]
    return obj

# ==============================
# 4) Employee helpers (simple behavior)
# ==============================
def find_employee_info(q: str):
    """
    Simple behavior:
    - Try to find employee by:
      1) Employee ID (any 3+ digit number)
      2) Email appearing in the text
      3) Name contained in the text (using 'name' column)
    """
    q_low = (q or "").lower()

    # 1) by numeric employee_id (e.g. 1006)
    if "employee_id" in employees.columns:
        m = re.search(r"\b\d{3,}\b", q_low)
        if m:
            emp_id = m.group()
            row = employees[employees["employee_id"].astype(str) == emp_id]
            if len(row) > 0:
                return row.iloc[0].to_dict()

    # 2) by email (contains)
    if "email" in employees.columns:
        for _, r in employees.iterrows():
            em = str(r.get("email", "")).lower()
            if em and em in q_low:
                return r.to_dict()

    # 3) by name (contains)
    if "name" in employees.columns:
        for _, r in employees.iterrows():
            nm = str(r.get("name", "")).lower()
            if nm and nm in q_low:
                return r.to_dict()

    return None

def g(row: dict, key: str, default: str = "-"):
    """Safe getter for employee dict."""
    val = row.get(key, row.get(key.lower()))
    if isinstance(val, (float, np.floating)) and pd.isna(val):
        return default
    return val if val not in [None, "nan", "NaN"] else default

BASIC_FIELDS_ORDER = [
    ("name",          "الاسم",           "Name"),
    ("employee_id",   "الرقم الوظيفي",   "Employee ID"),
    ("job_title",     "المسمى الوظيفي", "Job title"),
    ("department",    "القسم",           "Department"),
    ("location_name", "المقر",           "Location"),
    ("hire_date",     "تاريخ التعيين",   "Hire date"),
    ("leave_balance", "رصيد الإجازات",   "Leave balance"),
    ("email",         "البريد الوظيفي",  "Email"),
]

def render_employee_summary(emp: dict, lang: str) -> str:
    """Return compact, human-friendly summary for one employee."""
    lines = []
    if lang == "ar":
        lines.append("معلومات الموظف:")
        for key, ar_label, _ in BASIC_FIELDS_ORDER:
            if key in emp or key.lower() in emp:
                lines.append(f"- {ar_label}: {g(emp, key)}")
    else:
        lines.append("Employee info:")
        for key, _, en_label in BASIC_FIELDS_ORDER:
            if key in emp or key.lower() in emp:
                lines.append(f"- {en_label}: {g(emp, key)}")
    return "\n".join(lines)

def render_single_field(emp: dict, field: str, lang: str) -> str:
    """Return one-line answer for a specific employee field."""
    name  = g(emp, "name", "")
    empid = g(emp, "employee_id", "")
    value = g(emp, field, "-")

    labels_ar = {
        "email":              "البريد الوظيفي",
        "department":         "القسم",
        "job_title":          "المسمى الوظيفي",
        "hire_date":          "تاريخ التعيين",
        "location_name":      "المقر",
        "grade_name":         "الدرجة",
        "leave_balance":      "رصيد الإجازات",
        "total_compensation": "إجمالي التعويض",
    }
    labels_en = {
        "email":              "Email",
        "department":         "Department",
        "job_title":          "Job title",
        "hire_date":          "Hire date",
        "location_name":      "Location",
        "grade_name":         "Grade",
        "leave_balance":      "Leave balance",
        "total_compensation": "Total compensation",
    }

    label = labels_ar.get(field) if lang == "ar" else labels_en.get(field, field)
    if lang == "ar":
        who = f" للموظف {empid}" if empid else ""
        who = f"{who} ({name})" if name else who
        return f"{label}{who}: {value}"
    else:
        who = f" for employee {empid}" if empid else ""
        who = f"{who} ({name})" if name else who
        return f"{label}{who}: {value}"

# --- Arabic normalization (light) ---
AR_DIAC = re.compile(r"[\u064B-\u0652]")

def normalize_ar(s: str) -> str:
    """Light Arabic normalization to help keyword matching."""
    s = (s or "").strip().lower()
    s = AR_DIAC.sub("", s)  # remove diacritics
    s = s.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا")
    s = s.replace("ى", "ي").replace("ؤ", "و").replace("ئ", "ي")
    s = s.replace("ة", "ه")  # taa marbouta -> haa
    s = s.replace("ـ", "")   # tatweel
    if s.startswith("ال"):   # remove starting "ال"
        s = s[2:]
    return s

# ==============================
# 5) Intent detection (field)
# ==============================
FIELD_ALIASES = {
    "email":              ["email", "mail", "ايميل", "البريد", "البريد الإلكتروني", "البريد الوظيفي"],
    "department":         ["department", "dept", "القسم", "إدارة", "الادارة"],
    "job_title":          ["job title", "job", "وظيفة", "المسمى", "المسمى الوظيفي"],
    "hire_date":          ["hire date", "join date", "تاريخ التعيين", "تاريخ الانضمام"],
    "location_name":      ["location", "city", "موقع", "مدينة", "المقر"],
    "grade_name":         ["grade", "درجة", "المستوى"],
    "leave_balance":      ["leave balance", "leave", "رصيد الاجازات", "رصيد الإجازات", "الإجازة", "اجازة", "accrual"],
    "total_compensation": ["total compensation", "compensation", "salary total", "إجمالي التعويض", "إجمالي الراتب"],
}

def expand_en_syns(words, max_per_word: int = 6):
    """Expand English keys with WordNet synonyms."""
    out = set()
    for w in words:
        if not w:
            continue
        out.add(w.lower())
        for syn in wn.synsets(w):
            for lemma in syn.lemmas():
                term = lemma.name().replace("_", " ").lower()
                if term.isascii() and len(term) <= 30:
                    out.add(term)
    return list(out)[: max(10, min(50, len(out)))]

def expand_field_aliases(base: dict) -> dict:
    """Add English synonyms (WordNet) into FIELD_ALIASES."""
    expanded = {}
    for field, keys in base.items():
        en = [k for k in keys if re.fullmatch(r"[A-Za-z ][A-Za-z ]*", k or "")]
        ar = [k for k in keys if k and not re.fullmatch(r"[A-Za-z ][A-Za-z ]*", k)]
        en_exp = expand_en_syns(en)
        merged = set(keys) | set(en_exp) | set(ar)
        expanded[field] = sorted({m.strip().lower() for m in merged if m and len(m.strip()) > 0})
    return expanded

FIELD_ALIASES = expand_field_aliases(FIELD_ALIASES)
ALLOWED_FIELDS = list(FIELD_ALIASES.keys())

def detect_requested_field(question: str) -> str | None:
    """Fast keyword-based field detection (Arabic + English)."""
    q_en = (question or "").lower().strip()
    q_ar = normalize_ar(question or "")

    for canonical, keys in FIELD_ALIASES.items():
        for k in keys:
            if not k:
                continue
            # English key
            if re.fullmatch(r"[A-Za-z0-9 _-]+", k):
                if k in q_en:
                    return canonical
            else:  # Arabic key
                if normalize_ar(k) in q_ar:
                    return canonical
    return None

def detect_requested_field_llm(question: str) -> str | None:
    """LLM fallback: map question -> one of ALLOWED_FIELDS or 'general'."""
    system_prompt = (
        "You identify which single HR employee field the user requests.\n"
        "Allowed fields: email, department, job_title, hire_date, "
        "location_name, grade_name, leave_balance, total_compensation.\n"
        "If the question is about general employee info, respond with 'general'. "
        "Return ONLY the field name (lowercase) or 'general'."
    )
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        temperature=0,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": question},
        ],
    )
    field = (resp.choices[0].message.content or "").strip().lower()
    if field in ALLOWED_FIELDS:
        return field
    return None  # treat 'general'/unknown as None

def detect_requested_field_hybrid(question: str) -> str | None:
    """First keyword-based, then fallback to LLM if unclear."""
    f = detect_requested_field(question)
    if f:
        return f
    try:
        return detect_requested_field_llm(question)
    except Exception:
        return None

# ==============================
# 6) Conversation history helpers
# ==============================
def build_history_text(max_messages: int = 6) -> str:
    """Build compact text representation of last N messages for context."""
    lines = []
    for m in conversation_history[-max_messages:]:
        role = m.get("role", "user")
        prefix = "User" if role == "user" else "Assistant"
        content = m.get("content", "")
        lines.append(f"{prefix}: {content}")
    return "\n".join(lines)

# ==============================
# 7) Smalltalk / Greetings
# ==============================
WELCOME_AR = (
    "أهلًا بك 👋\n"
    "أنا مساعد الموارد البشرية. أجاوب سياسات الشركة ورصيد الإجازات وبيانات الموظفين.\n"
    "جرّب: «ما هي سياسة الإجازات السنوية؟» أو «أعطني بريد الموظف 1001»."
)
WELCOME_EN = (
    "Welcome 👋\n"
    "I'm the HR assistant. I can answer company policies and employee info.\n"
    "Try: “What is the annual leave policy?” or “Show the email of employee 1001”."
)

def detect_smalltalk(q: str) -> str | None:
    ql = (q or "").strip().lower()

    # تحيات
    if any(x in ql for x in [
        "مرحبا", "هلا", "السلام عليكم", "صباح الخير", "مساء الخير",
        "hi", "hello", "hey", "good morning", "good evening"
    ]):
        return "greet"

    # شكر
    if any(x in ql for x in ["شكرا", "ثانكس", "مشكور", "thanks", "thank you", "thx"]):
        return "thanks"

    # من أنت؟ مين أنت؟ من أنا؟ مين أنا؟
    if any(x in ql for x in [
        "من انت", "مين انت", "وش تسوي", "وش دورك",
        "من انا", "مين انا",
        "who are you", "what can you do", "who am i"
    ]):
        return "who"

    # طلب مساعدة
    if any(x in ql for x in ["ساعدني", "مساعدة", "كيف أستخدم", "help", "how to use"]):
        return "help"

    return None


def smalltalk_reply(intent: str, lang: str) -> str:
    if intent == "greet":
        return WELCOME_AR if lang == "ar" else WELCOME_EN

    if intent == "thanks":
        return "العفو 🙏، كيف أقدر أساعدك بعد؟" if lang == "ar" else "You're welcome 🙏. How else can I help?"

    if intent == "who":
        if lang == "ar":
            return (
                "أنا مساعد الموارد البشرية.\n"
                "أقدر أجاوبك على سياسات الشركة ورصيد الإجازات وبيانات الموظفين.\n"
                "اكتب لي رقم الموظف أو اسمه أو إيميله، وأنا أجيب لك كل التفاصيل."
            )
        else:
            return (
                "I'm the HR assistant.\n"
                "I can answer company policies, leave balance, and employee information.\n"
                "Give me an employee ID, name, or email and I'll show you the details."
            )

    if intent == "help":
        return (
            "اكتب رقم الموظف أو اسمه أو اسأل عن سياسة: مثل الإجازات، بدل السكن، إنهاء الخدمة."
        ) if lang == "ar" else (
            "Ask about any policy or provide an employee ID/name/email for details."
        )

    return WELCOME_AR if lang == "ar" else WELCOME_EN

def translate_ar_to_en(text: str) -> str:
    """
    Translate Arabic HR question to English for better policy retrieval.
    If text is not Arabic or translation fails, return original text.
    """
    if detect_lang(text) != "ar":
        return text

    system = (
        "You are a professional translator for HR/legal content. "
        "Translate the following Arabic question into clear English. "
        "Return ONLY the translation."
    )
    try:
        translation = llm_call(
            [
                {"role": "system", "content": system},
                {"role": "user",   "content": text},
            ],
            model="gpt-4o-mini",
            temperature=0.0,
        )
        return translation.strip()
    except Exception:
        return text

# Rule-based mapping for some Arabic policy phrases
def map_arabic_policy_query(q: str) -> str:
    """Map certain Arabic keywords to richer English queries for retrieval."""
    q_norm = normalize_ar(q)

    if "انتداب" in q_norm:
        return "business trip delegation assignment travel policy allowance per diem"
    if "بدل سكن" in q_norm or "بدل السكن" in q_norm:
        return "housing allowance policy monthly housing 25% of basic salary if no in-kind housing"
    if "بدل انتقال" in q_norm or "بدل المواصلات" in q_norm or "بدل نقل" in q_norm:
        return "transportation allowance policy monthly transportation allowance"

    return q

# ==============================
# 8) Policy answer via RAG
# ==============================
def answer_policy(q: str, top_k: int = 8) -> tuple[str, dict]:
    """
    Retrieve policy text using FAISS + rerank with cross-encoder.
    For Arabic:
      - apply simple mapping for some keywords
      - translate to English
      - combine both Arabic + English for embeddings
    Returns (context_text, top_meta) where top_meta has:
      - policy_no
      - department
      - title
    """
    lang = detect_lang(q)

    q_for_embed = q
    if lang == "ar":
        q_mapped = map_arabic_policy_query(q)
        q_en = translate_ar_to_en(q_mapped)
        q_for_embed = f"{q_mapped} / {q_en}"

    q_e5 = "query: " + q_for_embed
    docs_sim = vs.similarity_search(q_e5, k=top_k)
    if not docs_sim:
        return "", {}

    pairs = [[q_for_embed, d.page_content] for d in docs_sim]
    scores = cross_enc.predict(pairs).tolist()
    ranked = sorted(zip(docs_sim, scores), key=lambda x: x[1], reverse=True)

    top_snips = []
    top_doc = ranked[0][0]

    top_meta = {
        "policy_no":  top_doc.metadata.get("policy_no", "") or "",
        "department": top_doc.metadata.get("department", "") or "",
        "title":      top_doc.metadata.get("title", "") or "",
    }

    for d, _ in ranked[:3]:
        text = d.page_content.replace("passage: ", "", 1)
        top_snips.append(text)

    context = "\n\n---\n\n".join(top_snips)[:3000]
    return context, top_meta

# ==============================
# 9) Decide when to use employee vs policy
# ==============================
def should_route_to_employee(q: str, requested_field: str | None) -> bool:
    """
    Decide if this query should go to the employee route.
    Rules:
      - If a specific employee field is detected -> employee.
      - If query has strong policy words (policy, allowance, leave, visa, termination...)
        and NO strong "info" words -> treat as policy even if employee ID exists.
      - If query has "info" / "email" / "department" etc and no strong policy words -> employee.
    """
    if requested_field:
        return True

    q_low = (q or "").lower()
    q_norm = normalize_ar(q)

    policy_words_en = [
        "policy", "allowance", "visa", "ticket", "termination",
        "resignation", "end of service", "leave"
    ]
    policy_words_ar = [
        "سياسه", "سياسة", "بدل", "اجازه", "اجازة",
        "تذكره", "انهاء", "نهايه الخدمه", "نهاية الخدمة", "نهاية الخدمه"
    ]

    info_words_en = [
        "info", "information", "details", "show", "give me",
        "what is", "who is", "email", "department", "job title"
    ]
    info_words_ar = [
        "معلومات", "البريد", "القسم", "المسمى", "رصيد",
        "ما هو", "ماهي", "ما هي", "من هو"
    ]

    has_policy = any(w in q_low for w in policy_words_en) or any(w in q_norm for w in policy_words_ar)
    has_info   = any(w in q_low for w in info_words_en) or any(w in q_norm for w in info_words_ar)

    # If clearly about policy -> do NOT route to employee
    if has_policy and not has_info:
        return False

    # If clearly asking about employee info -> employee
    if has_info:
        return True

    # If query explicitly mentions "employee" / "الموظف" without clear policy words -> employee
    if "employee" in q_low or "الموظف" in q_norm:
        return not has_policy

    # Default: not confident -> treat as policy (safer for your use-case)
    return False

# ==============================
# 10) Main router
# ==============================
def hr_answer(q: str) -> str:
    """
    Main router:
    - Smalltalk
    - Employee questions (stateless)
    - Policy questions via RAG (with history only for pronouns)
    """
    global conversation_history

    lang = detect_lang(q)

    # ---- Smalltalk first ----
    st = detect_smalltalk(q)
    if st:
        return smalltalk_reply(st, lang)

    # ---- A) Employee route (with gating) ----
    emp = find_employee_info(q)
    requested_field = None
    if emp:
        requested_field = detect_requested_field_hybrid(q)

    if emp and should_route_to_employee(q, requested_field):
        emp = make_json_safe(emp)
        if requested_field and (requested_field in emp or requested_field.lower() in emp):
            return render_single_field(emp, requested_field, lang)
        return render_employee_summary(emp, lang)

    # ---- B) Policy route (RAG) ----
    context, meta = answer_policy(q)
    if not context:
        if lang == "ar":
            return (
                "لم أجد سياسة مرتبطة بسؤالك في السجلات الحالية. "
                "حاول أن تعيد صياغة سؤالك أو توضّح السياسة أكثر."
            )
        else:
            return (
                "I couldn't find any policy related to your question in the current records. "
                "Please rephrase or specify the policy."
            )

    history_text = build_history_text()

    if lang == "ar":
        system = (
            "أنت مساعد موارد بشرية يجيب بالعربية فقط. "
            "اعتمد فقط على النص الموجود داخل [CONTEXT] للحقائق والسياسات. "
            "يمكنك استخدام [HISTORY] فقط لفهم الضمائر وسياق الأسئلة السابقة، "
            "لكن لا تضف معلومات غير موجودة في [CONTEXT]. "
            "كن موجزًا ودقيقًا."
        )
    else:
        system = (
            "You are an HR assistant. Answer in English only. "
            "Use ONLY the content in [CONTEXT] for facts/policies. "
            "You may use [HISTORY] only to resolve pronouns and understand the dialogue context, "
            "but do NOT invent facts beyond [CONTEXT]. "
            "Be concise and precise."
        )

    user_prompt = (
        f"[HISTORY]\n{history_text}\n\n"
        f"[QUESTION]\n{q}\n\n"
        f"[CONTEXT]\n{context}"
    )

    messages = [
        {"role": "system", "content": system},
        {"role": "user",   "content": user_prompt},
    ]
    base_answer = llm_call(messages)

    # ---- Add policy source (policy_no + department + title) ----
    policy_no = (meta.get("policy_no") or "").strip()
    dept      = (meta.get("department") or "").strip()
    title     = (meta.get("title") or "").strip()

    if lang == "ar":
        src_parts = []
        if policy_no:
            src_parts.append(f"رقم السياسة: {policy_no}")
        if dept:
            src_parts.append(f"الإدارة/القسم: {dept}")
        if title:
            src_parts.append(f"العنوان: {title}")
        if src_parts:
            base_answer += "\n\nالمصدر:\n- " + "\n- ".join(src_parts)
    else:
        src_parts = []
        if policy_no:
            src_parts.append(f"Policy No: {policy_no}")
        if dept:
            src_parts.append(f"Department: {dept}")
        if title:
            src_parts.append(f"Title: {title}")
        if src_parts:
            base_answer += "\n\nSource:\n- " + "\n- ".join(src_parts)

    return base_answer


# ==============================
# Entry point for backend usage
# ==============================
if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        question = " ".join(sys.argv[1:])
    else:
        question = input("You: ").strip()

    answer = hr_answer(question)
    print(answer)

